version: '3'
services:
  jenkins:
    container_name: jenkins-data
    image: test02_centOS_jenkins
    ports:
         - 8080:8080
         - 50000:50000
    volumes:
         - jenkins_data:/var/jenkins_home
    networks:
         - net
networks:
         net: